/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package ventanas;

import com.sun.glass.events.KeyEvent;
import java.awt.Desktop;
import java.net.URI;
import javax.swing.JOptionPane;

/**
 *
 * @author 54934
 */
public class VentanaMoneda extends javax.swing.JFrame {

    /**
     * Creates new form VentanaMoneda
     */
    public VentanaMoneda() {
        initComponents();
        this.setLocationRelativeTo(null);
        this.setDefaultCloseOperation(EXIT_ON_CLOSE);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        txtCantidadDineroIngresado = new javax.swing.JTextField();
        jLabel2 = new javax.swing.JLabel();
        cbxSelectorMonedas1 = new javax.swing.JComboBox<>();
        btnVolverVentanaPrincipal = new javax.swing.JButton();
        jButton2 = new javax.swing.JButton();
        btnCalularConversionMoneda = new javax.swing.JButton();
        jLabel3 = new javax.swing.JLabel();
        cbxSelectorMonedas2 = new javax.swing.JComboBox<>();
        lblResultado = new javax.swing.JLabel();
        lblLogoAlura = new javax.swing.JLabel();
        jSeparator1 = new javax.swing.JSeparator();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel1.setPreferredSize(new java.awt.Dimension(610, 529));

        jLabel1.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        jLabel1.setText("CONVERSOR DE MONEDAS");

        txtCantidadDineroIngresado.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        txtCantidadDineroIngresado.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                txtCantidadDineroIngresadoKeyTyped(evt);
            }
        });

        jLabel2.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel2.setText("Ingresar cantidad de dinero:");

        cbxSelectorMonedas1.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        cbxSelectorMonedas1.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Seleccionar moneda...", "BOLÍVAR VENEZOLANO", "CORONA CHECA", "CORONA DANESA", "CORONA NORUEGA", "CORONA SUECA", "DINAR KUWAIT", "DIRHAM EMIRATOS", "DÓLAR AUSTRALIANO", "DÓLAR CANADIENSE", "DÓLAR EEUU", "DÓLAR HONG KONG", "DÓLAR NEOZELANDÉS", "DÓLAR SINGAPUR", "EURO", "FLORÍN HÚNGARO", "FRANCO SUIZO", "LIBRA", "LIRA TURCA", "LITAS LITUANO", "PESO ARGENTINO", "PESO CHILENO", "PESO COLOMBIANO", "PESO MEXICANO", "PESO URUGUAYO", "RAND SUDAFRICANO", "REAL BRASILEÑO", "RIAL SAUDÍ", "RINGGIT MALASIO", "RUBLO RUSO", "RUPIA INDIA", "SHEKEL ISRAELI", "YEN", "YUAN", "ZLOTY POLACO" }));

        btnVolverVentanaPrincipal.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        btnVolverVentanaPrincipal.setText(" Volver");
        btnVolverVentanaPrincipal.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnVolverVentanaPrincipalActionPerformed(evt);
            }
        });

        jButton2.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jButton2.setText("Salir");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });

        btnCalularConversionMoneda.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        btnCalularConversionMoneda.setText("Calcular");
        btnCalularConversionMoneda.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCalularConversionMonedaActionPerformed(evt);
            }
        });

        jLabel3.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel3.setText("Convertir a moneda");

        cbxSelectorMonedas2.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        cbxSelectorMonedas2.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Seleccionar moneda...", "BOLÍVAR VENEZOLANO", "CORONA CHECA", "CORONA DANESA", "CORONA NORUEGA", "CORONA SUECA", "DINAR KUWAIT", "DIRHAM EMIRATOS", "DÓLAR AUSTRALIANO", "DÓLAR CANADIENSE", "DÓLAR EEUU", "DÓLAR HONG KONG", "DÓLAR NEOZELANDÉS", "DÓLAR SINGAPUR", "EURO", "FLORÍN HÚNGARO", "FRANCO SUIZO", "LIBRA", "LIRA TURCA", "LITAS LITUANO", "PESO ARGENTINO", "PESO CHILENO", "PESO COLOMBIANO", "PESO MEXICANO", "PESO URUGUAYO", "RAND SUDAFRICANO", "REAL BRASILEÑO", "RIAL SAUDÍ", "RINGGIT MALASIO", "RUBLO RUSO", "RUPIA INDIA", "SHEKEL ISRAELI", "YEN", "YUAN", "ZLOTY POLACO" }));

        lblResultado.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        lblResultado.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblResultado.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);

        lblLogoAlura.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/logoAlura.png"))); // NOI18N

        jLabel4.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/211904_social_github_icon.png"))); // NOI18N
        jLabel4.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jLabel4.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabel4MouseClicked(evt);
            }
        });

        jLabel5.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/5279112_camera_instagram_social media_instagram logo_icon.png"))); // NOI18N
        jLabel5.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jLabel5.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabel5MouseClicked(evt);
            }
        });

        jLabel6.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/5279114_linkedin_network_social network_linkedin logo_icon.png"))); // NOI18N
        jLabel6.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jLabel6.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabel6MouseClicked(evt);
            }
        });

        jLabel8.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel8.setText("© Emilio Elias 2022 ");

        jLabel7.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/134164_money_exchange_cash_currency_icon.png"))); // NOI18N

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(cbxSelectorMonedas2, javax.swing.GroupLayout.PREFERRED_SIZE, 177, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(24, 24, 24)
                        .addComponent(jLabel3)))
                .addGap(218, 218, 218))
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(207, 207, 207)
                        .addComponent(jLabel2))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(30, 30, 30)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(lblResultado, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGap(0, 0, Short.MAX_VALUE)
                                .addComponent(lblLogoAlura)
                                .addGap(94, 94, 94)
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addGroup(jPanel1Layout.createSequentialGroup()
                                        .addComponent(txtCantidadDineroIngresado, javax.swing.GroupLayout.PREFERRED_SIZE, 94, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addGap(18, 18, 18)
                                        .addComponent(cbxSelectorMonedas1, javax.swing.GroupLayout.PREFERRED_SIZE, 177, javax.swing.GroupLayout.PREFERRED_SIZE))
                                    .addComponent(jLabel1))
                                .addGap(70, 70, 70)
                                .addComponent(jLabel7)
                                .addGap(23, 23, 23))
                            .addGroup(javax.swing.GroupLayout.Alignment.LEADING, jPanel1Layout.createSequentialGroup()
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                    .addComponent(jSeparator1, javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel8, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, 547, Short.MAX_VALUE))
                                .addGap(0, 0, Short.MAX_VALUE)))))
                .addGap(32, 32, 32))
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(192, 192, 192)
                        .addComponent(jLabel4)
                        .addGap(38, 38, 38)
                        .addComponent(jLabel5)
                        .addGap(43, 43, 43)
                        .addComponent(jLabel6))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(135, 135, 135)
                        .addComponent(btnCalularConversionMoneda, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(btnVolverVentanaPrincipal, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(21, 21, 21)
                        .addComponent(jButton2, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGap(23, 23, 23)
                                .addComponent(lblLogoAlura, javax.swing.GroupLayout.PREFERRED_SIZE, 59, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGap(37, 37, 37)
                                .addComponent(jLabel1)))
                        .addGap(20, 20, 20)
                        .addComponent(jLabel2)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(txtCantidadDineroIngresado, javax.swing.GroupLayout.DEFAULT_SIZE, 37, Short.MAX_VALUE)
                            .addComponent(cbxSelectorMonedas1))
                        .addGap(18, 18, 18)
                        .addComponent(jLabel3)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(cbxSelectorMonedas2, javax.swing.GroupLayout.PREFERRED_SIZE, 36, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(23, 23, 23)
                        .addComponent(jLabel7)))
                .addGap(27, 27, 27)
                .addComponent(lblResultado)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 82, Short.MAX_VALUE)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnVolverVentanaPrincipal, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jButton2, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnCalularConversionMoneda, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addComponent(jSeparator1, javax.swing.GroupLayout.PREFERRED_SIZE, 10, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel4)
                    .addComponent(jLabel5)
                    .addComponent(jLabel6))
                .addGap(18, 18, 18)
                .addComponent(jLabel8)
                .addGap(22, 22, 22))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, 612, javax.swing.GroupLayout.PREFERRED_SIZE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jLabel4MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel4MouseClicked
        try {
            if (Desktop.isDesktopSupported()) {
                Desktop desktop = Desktop.getDesktop();
                if (desktop.isSupported(Desktop.Action.BROWSE)) {
                    desktop.browse(new URI("https://github.com/emilioelias"));
                }
            }
        } catch (Exception e) {
            e.printStackTrace();
        }        
    }//GEN-LAST:event_jLabel4MouseClicked

    private void btnCalularConversionMonedaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCalularConversionMonedaActionPerformed

        String[][] monedas = {
            {"BOLÍVAR VENEZOLANO", "33263.46"},
            {"CORONA CHECA", "24.47"},
            {"CORONA DANESA", "7.42"},
            {"CORONA NORUEGA", "9.8165756726182"},
            {"CORONA SUECA", "10.675852920095"},
            {"DINAR KUWAIT", "0.30795314588354"},
            {"DIRHAM EMIRATOS", "3.671788531732"},
            {"DÓLAR AUSTRALIANO", "1.4589239766082"},
            {"DÓLAR CANADIENSE", "1.3098483028745"},
            {"DÓLAR EEUU", "1.0"},
            {"DÓLAR HONG KONG", "7.8462058608462"},
            {"DÓLAR NEOZELANDÉS", "1.6301758570273"},
            {"DÓLAR SINGAPUR", "1.3979633720775"},
            {"EURO", "0.997904"},
            {"FLORÍN HÚNGARO", "401.24809006836"},
            {"FRANCO SUIZO", "0.97365511925496"},
            {"LIBRA", "0.85767425870219"},
            {"LIRA TURCA", "18.172785547786"},
            {"LITAS LITUANO", "2.9340021227989"},
            {"PESO ARGENTINO", "138.59777777778"},
            {"PESO CHILENO", "887.81494661922"},
            {"PESO COLOMBIANO", "4415.5044247788"},
            {"PESO MEXICANO", "20.146652668982"},
            {"PESO URUGUAYO", "40.704193179964"},
            {"RAND SUDAFRICANO", "16.972311041567"},
            {"REAL BRASILEÑO", "5.1058830752858"},
            {"RIAL SAUDÍ", "3.7566029212468"},
            {"RINGGIT MALASIO", "4.4753072024397"},
            {"RUBLO RUSO", "60.873787592265"},
            {"RUPIA INDIA", "79.774882084899"},
            {"SHEKEL ISRAELI", "3.6864923972633"},
            {"YEN", "138.61703014308"},
            {"YUAN", "6.9094962783452"},
            {"ZLOTY POLACO", "4.7180883757435"}
        };

        double dblCantidadDineroIngresado = Double.parseDouble(txtCantidadDineroIngresado.getText());
        double dblResultado;
        String strResultado;
        String monedaSeleccionada1 = (String) cbxSelectorMonedas1.getSelectedItem();
        String monedaSeleccionada2 = (String) cbxSelectorMonedas2.getSelectedItem();
        String strValorMoneda1 = "";
        String strValorMoneda2 = "";
        double dblValorMoneda1 = 0;
        double dblValorMoneda2 = 0;

        if (monedaSeleccionada1.equals("Seleccionar moneda...")) {
            JOptionPane.showMessageDialog(null, "Seleccione una moneda");
        } else if (monedaSeleccionada2.equals("Seleccionar moneda...")) {
            JOptionPane.showMessageDialog(null, "Seleccione una moneda");
        } else {
            for (int ren = 0; ren <= monedas.length-1; ren++) {
                if (monedas[ren][0].equals(monedaSeleccionada1)) {
                    strValorMoneda1 = monedas[ren][1];
                    dblValorMoneda1 = Double.parseDouble(strValorMoneda1);
                    System.out.println(dblValorMoneda1);
                }
                if (monedas[ren][0].equals(monedaSeleccionada2)) {
                    strValorMoneda2 = monedas[ren][1];
                    dblValorMoneda2 = Double.parseDouble(strValorMoneda2);
                    System.out.println(dblValorMoneda2);
                }
                dblResultado = Math.round((dblCantidadDineroIngresado * dblValorMoneda2 / dblValorMoneda1) * 100) / 100;
                strResultado = Double.toString(dblResultado);

                lblResultado.setText(dblCantidadDineroIngresado + " " + monedaSeleccionada1 + " equivale a " + strResultado + " " + monedaSeleccionada2);
            }
        }
    }//GEN-LAST:event_btnCalularConversionMonedaActionPerformed

    private void btnVolverVentanaPrincipalActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnVolverVentanaPrincipalActionPerformed

        VentanaPrincipal ventanaPrincipal = new VentanaPrincipal();
        ventanaPrincipal.setVisible(true);
        this.setVisible(false);
    }//GEN-LAST:event_btnVolverVentanaPrincipalActionPerformed

    private void txtCantidadDineroIngresadoKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtCantidadDineroIngresadoKeyTyped

        //Validacion del campo para ingreso de datos solo decimal con "."
        char caracter = evt.getKeyChar();

        if ((caracter < '0' || caracter > '9')
            && (caracter != KeyEvent.VK_BACKSPACE)
            && (caracter != '.' || txtCantidadDineroIngresado.getText().contains("."))) {
            evt.consume();
        }
    }//GEN-LAST:event_txtCantidadDineroIngresadoKeyTyped

    private void jLabel5MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel5MouseClicked
        try {
            if (Desktop.isDesktopSupported()) {
                Desktop desktop = Desktop.getDesktop();
                if (desktop.isSupported(Desktop.Action.BROWSE)) {
                    desktop.browse(new URI("https://www.instagram.com/emilioe375"));
                }
            }
        } catch (Exception e) {
            e.printStackTrace();
        }    
    }//GEN-LAST:event_jLabel5MouseClicked

    private void jLabel6MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel6MouseClicked
        try {
            if (Desktop.isDesktopSupported()) {
                Desktop desktop = Desktop.getDesktop();
                if (desktop.isSupported(Desktop.Action.BROWSE)) {
                    desktop.browse(new URI("https://www.linkedin.com/in/emilioelias375"));
                }
            }
        } catch (Exception e) {
            e.printStackTrace();
        }  
    }//GEN-LAST:event_jLabel6MouseClicked

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        this.dispose();
    }//GEN-LAST:event_jButton2ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(VentanaMoneda.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(VentanaMoneda.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(VentanaMoneda.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(VentanaMoneda.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new VentanaMoneda().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnCalularConversionMoneda;
    private javax.swing.JButton btnVolverVentanaPrincipal;
    private javax.swing.JComboBox<String> cbxSelectorMonedas1;
    private javax.swing.JComboBox<String> cbxSelectorMonedas2;
    private javax.swing.JButton jButton2;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JSeparator jSeparator1;
    private javax.swing.JLabel lblLogoAlura;
    private javax.swing.JLabel lblResultado;
    private javax.swing.JTextField txtCantidadDineroIngresado;
    // End of variables declaration//GEN-END:variables
}
